server:
  port: 5000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

spring:
  application:
    name: service-zuul
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
#ribbon:
#  eureka:
#    enabled: false

zuul:
  routes:
    hiapi:
      path: /hiapi/**
      serviceId: eureka-client
    ribbonapi:
      path: /ribbonapi/**
      serviceId: eureka-ribbon-client
    feignapi:
      path: /feignapi/**
#      serviceId: hiapi-v1
      serviceId: eureka-feign-client
#  prefix: /v1
#hiapi-v1:
#  ribbon:
#    listOfServers: http://localhost:8762, http://localhost:8763